### ISSUE TITLE
Helm-resume does not resume helm-projectile-ag search correctly

### ISSUE THREAD

**Issue by greenrd** [bbatsov/helm-projectile#1]
helm-projectile-ag works fine for me, but when I use helm-resume to resume a previous search, I experience a couple of issues. Firstly, navigating to a file does not always work - sometimes the filename is incorrectly constructed based on the current directory of the buffer I was in instead of the root directory of the projectile project. Secondly, editing the search causes no results to be displayed (I suspect the same fundamental cause - searching in the subdirectory instead of the projectile root directory).

**Comment by xiongtx** [comment]
I cannot reproduce this issue.

If you're still encountering this after updating to the latest version of `helm-projectile`, please provide a minimal project (Git repo) and more details via the issue template.

**Comment by xiongtx** [comment]
@jlisee For that particular issue, see cosmicexplorer/helm-rg#11.
