### ISSUE TITLE
delete disorderly in minibuffer 

### ISSUE THREAD

**Issue by ambjlon** [bbatsov/helm-projectile#100]
When delete in minibuffer, the display is in wild disorder as below:
![2018-03-30 10 49 55](https://user-images.githubusercontent.com/4489822/38122702-1c0cb726-3409-11e8-8425-8bd403f7ec30.gif)

**Comment by xiongtx** [comment]
Which command is this?

That looks like `helm-find-files`, which is part of [Helm](https://github.com/emacs-helm/helm) itself, not `helm-projectile`. But I cannot reproduce w/ `helm-find-files`.

**Comment by Asalle** [comment]
Cannot reproduce it as well, @ambjlon could you provide more details?

**Comment by xiongtx** [comment]
Going to close this as it cannot be reproduced. Feel free to reopen w/ more info.
