### ISSUE TITLE
get rid of creating non-existing files

### ISSUE THREAD

**Issue by introom** [bbatsov/helm-projectile#104]
After upgrading projectile/helm-projectile, the first two entries when search some file with the helm-projectile command now becomes creating the non-existing files:

e.g.,
![image](https://user-images.githubusercontent.com/669045/39588165-ce263772-4f2d-11e8-9096-b3edcf8a1122.png)

Possible to get rid of that?

**Comment by xiongtx** [comment]
No. This is a feature introduced for #42.

**Comment by introom** [comment]
possible to add an option to move the [?] to the very last of the entries ?

**Comment by xiongtx** [comment]
The selector should be on the first non-`[?]` candidate by default. Any reason that's not sufficient?

**Comment by introom** [comment]
it takes up spaces and is oftentimes useless because we wants to search file, not to create file.

**Comment by introom** [comment]
it takes up spaces and is oftentimes useless because we wants to search file, not to create file.
