### ISSUE TITLE
Possible to stop helm-projectile-find-files from listing all files when first run?

### ISSUE THREAD

**Issue by chris-kahn** [bbatsov/helm-projectile#105]
When running `helm-projectile-find-files` it seems like the default search is to list all files in the project, and then narrow down as I start typing. However this makes the helm minibuffer open really slowly.

Is there a way to stop it from listing all files before I have typed any search input?

**Comment by xiongtx** [comment]
> Is there a way to stop it from listing all files before I have typed any search input?

It would need to search through all project files when you begin typing, so I'm not sure what would be gained.

> this makes the helm minibuffer open really slowly.

How many files do you have in your project? #101 fixed an issue with performance; are upgraded to that?
