### ISSUE TITLE
helm-projectile cannot be installed from MELPA stable

### ISSUE THREAD

**Issue by dakrone** [bbatsov/helm-projectile#11]
According to the readme:

```
MELPA Stable

You can install the last stable version of helm-projectile from the MELPA Stable repository.
```

However, [no git tags for helm-projectile have been pushed](https://github.com/bbatsov/helm-projectile/releases), and the package does not show up in the listing for MELPA stable.

Could you tag a release and push it so it shows up on MELPA stable?

**Comment by codeitagile** [comment]
Same problem here

**Comment by favadi** [comment]
Same problem as https://github.com/bbatsov/persp-projectile/issues/2.

**Comment by DamienCassou** [comment]
Could you please tag the current commit so that the package appears on melpa stable? You can do it through github in the "releases" tab or through `git tag`. Thanks

**Comment by DamienCassou** [comment]
any news?

**Comment by z4139jq** [comment]
+1

**Comment by bbatsov** [comment]
> Could you please tag the current commit so that the package appears on melpa stable? You can do it through github in the "releases" tab or through git tag. Thanks

I know how to use `git`. :-) Guess I totally forgot about this.

**Comment by bbatsov** [comment]
Done.

**Comment by DamienCassou** [comment]
@bbatsov I know :-). I just copy/pasted this issue on several repositories (one guy asked me how to get a package on melpa stable, that's why I now explain it in all my requests).

Thank you
