### ISSUE TITLE
Does "C-c p 4 f" use helm UI?

### ISSUE THREAD

**Issue by foreverqihe** [bbatsov/helm-projectile#112]
This is just a question about if C-c p 4 f is supported
## Expected behavior

C-c p 4 f should show the helm UI

## Actual behavior

ido ui is displayed

## Steps to reproduce the problem

C-c p 4 f

## Environment & version information

- `helm-projectile` version: latest (updated everyday)
- `helm` version (in `helm-pkg.el`): latest
- `projectile` version (`M-x projectile-version`): latest
- Emacs version (`M-x emacs-version`): 26.1
- OS: Windows

**Comment by xiongtx** [comment]
`C-p 4 f` (`projectile-find-file-other-window`) is a Projectile command, not a `helm-projectile` command. 

To get Helm completion, set `projectile-completion-system` to `'helm` instead of `'ido` (the default).

**Comment by foreverqihe** [comment]
Thank you @xiongtx
