### ISSUE TITLE
helm-projectile-on doesn't activate key-bindings

### ISSUE THREAD

**Issue by dylangleason** [bbatsov/helm-projectile#116]
## Expected behavior

After enabling helm keybindings via `helm-projectile-on`, I should be able to use the prefix `C-c p` to  invoke helm-projectile operations. 

## Actual behavior

Enabling `helm-projectile-on` with projectile and helm enabled has no effect. helm-projectile commands do work, however (e.g. `helm-projectile-find-file` can be invoked manually via `helm M-x`). Note that the key binding for the relevant command doesn't show up next to the command listed when viewing in the minibuffer.

A / B testing this against a backup version (indicated below), which works, seems to indicate that there is a regression here.

## Steps to reproduce the problem

- With both helm and projectile-mode enabled, execute `M-x helm-projectile-on`. 
- Attempt to run `C-c p f` to find a file in the project.
- `C-c p is undefined` appears in the minibuffer / `*Messages*`.
- Note that executing the command via `helm M-x` still works, but that the keybinding is not indicated in the command list. (e.g. for `helm-projectile-find-file` it would indicate `(C-c p f)` next to the command name).

## Backtraces if necessary (`M-x toggle-debug-on-error`)

No errors indicated.

### Current configuration

- `helm-projectile` version: **`20180815.1514`**
- `helm` version (in `helm-pkg.el`): **`20181005.1844`**
- `projectile` version (`M-x projectile-version`): **`20181017.830`**
- Emacs version (`M-x emacs-version`): **`GNU Emacs 25.1.1 (x86_64-pc-linux-gnu) of 2017-09-14, modified by Debian`**
- OS: **`Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux`** (I also reproduced this on my other machine running macOS High Sierra)

### Last working configuration

- `helm-projectile` version: **`20180526.2204`**
- `helm` version (in `helm-pkg.el`): **`20180607.420`**
- `projectile` version (`M-x projectile-version`): **`20180316.2010`**

**Comment by dylangleason** [comment]
The only seemingly relevant [change](https://github.com/bbatsov/helm-projectile/commit/f95c555e95c87895b18b85d03686308706fe6dc6) that I can see was from 5 months ago, and it doesn't seem like it should affect the above behavior... I wonder if this is an issue with `helm` itself?

**Comment by kaustubhkurve** [comment]
It seems that the default keymap prefix for projectile (C-c p) was removed in [9c6e981](https://github.com/bbatsov/projectile/commit/9c6e9813abec6e067c659e9107bf356086a95e04). Setting the keymap prefix by adding `(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)` in the init file should restore the keybindings.

**Comment by dylangleason** [comment]
@kaustubhkurve 's proposed solution resolves this issue.
