### ISSUE TITLE
Markdown files take over keyboard input if follow mode is on.

### ISSUE THREAD

**Issue by vidjuheffex** [bbatsov/helm-projectile#118]
## Expected behavior
Pressing down through a list of project files in helm should go to the next item in the list

## Actual behavior
Works unless the list-item is a markdown file in which case it opens the file, and sends the down arrow command as cursor movement.

## Steps to reproduce the problem
Be in project, do helm-projectile-find-file, hit down arrow past a markdown file

## Environment & version information

- `helm-projectile` version: 20180815.1514
- `helm` version (in `helm-pkg.el`): 20181222.848
- `projectile` version (`M-x projectile-version`): 20181218.2023
- Emacs version (`M-x emacs-version`): 26.1
- OS: Mac OS X 10.13.6

![5c3e38e194254986748978](https://user-images.githubusercontent.com/3157835/51208100-57fe6780-18d2-11e9-95f9-d0b4b5fce3bb.gif)

**Comment by vidjuheffex** [comment]
Actually I dont think its the markdown file, I think thats a coincidence, I get "Error running timer: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")" in the messages window

**Comment by xiongtx** [comment]
What are you using to preview the files? I'd guess that's the problem. `helm-projectile` doesn't come w/ that functionality out of the box AFAIK.

![no-preview](https://user-images.githubusercontent.com/1624090/52873553-23194680-3104-11e9-95f4-818bcb9b7586.gif)

**Comment by xiongtx** [comment]
Closing as it doesn't seem like a `helm-projectile` issue.
