### ISSUE TITLE
Remove 'maintainer needed' announcement

### ISSUE THREAD

**Issue by azzamsa** [bbatsov/helm-projectile#119]
> The project is looking for more maintainers. I (Bozhidar) don't use Helm myself and don't have much time for the project, so I would definitely appreciate some help with it.

Since @xiongtx has joined the force as [stated here](https://github.com/bbatsov/helm-projectile/issues/63#issuecomment-275306761), is the announcement still relevant ?

**Comment by xiongtx** [comment]
More :open_hands:  make lighter work :smile:.

**Comment by azzamsa** [comment]
Sure, I use helm as my primary package. I will contribute here if I made some hacks. :)
