### ISSUE TITLE
helm-mini

### ISSUE THREAD

**Issue by user471** [bbatsov/helm-projectile#12]
Helm have this `helm-mini` command that shows `buffers` and `recentf` together.
`helm-projectile` could have similar command but with `buffers` and `recentf` from project.
Or maybe it could be a setting to change `helm-projectile` to use `recentf` instead of `files`

**Comment by xiongtx** [comment]
You can [customize](http://ergoemacs.org/emacs/emacs_custom_system.html) `helm-projectile-sources-list` to add `helm-source-projectile-recentf-list`.
