### ISSUE TITLE
helm-projectile-grep doesn't work, but projectile-grep work well

### ISSUE THREAD

**Issue by FavoRiteKK** [bbatsov/helm-projectile#120]
## Expected behavior

helm-projectile-grep works well

## Actual behavior

Error running timer 'helm-projectile-grep-or-ack': (void-function -union)

## Steps to reproduce the problem

type M-x helm-projectile-grep RET

## Backtraces if necessary (`M-x toggle-debug-on-error`)

Debugger entered--Lisp error: (void-function -union)
  -union(("TAGS") (".#*" "*.o" "*~" "*.bin" "*.lbin" "*.so" "*.a" "*.ln" "*.blg" "*.bbl" "*.elc" "*.lof" "*.glo" "*.idx" "*.lot" "*.fmt" "*.tfm" "*.class" "*.fas" "*.lib" "*.mem" "*.x86f" "*.sparcf" "*.dfsl" "*.pfsl" "*.d64fsl" "*.p64fsl" "*.lx64fsl" "*.lx32fsl" "*.dx64fsl" "*.dx32fsl" "*.fx64fsl" "*.fx32fsl" "*.sx64fsl" "*.sx32fsl" "*.wx64fsl" "*.wx32fsl" "*.fasl" "*.ufsl" "*.fsl" "*.dxl" "*.lo" "*.la" "*.gmo" "*.mo" "*.toc" "*.aux" "*.cp" "*.fn" "*.ky" ...))
  helm-projectile-grep-or-ack("\~/workspace/shared/" nil)
  apply(helm-projectile-grep-or-ack ("\~/workspace/shared/" nil))
  timer-event-handler([t 23696 37954 478834 nil helm-projectile-grep-or-ack ("~/workspace/shared/" nil) nil 505000])

## Environment & version information

- `helm-projectile` version: 0.14.0
- `helm` version (in `helm-pkg.el`): 3.1
- `projectile` version (`M-x projectile-version`): 2.0.0
- Emacs version (`M-x emacs-version`): 25.2.1
- OS: Ubuntu 18.04.01

**Comment by FavoRiteKK** [comment]
Error is not same as #86

**Comment by FavoRiteKK** [comment]
Can be fixed by opening helm-projectile.el, add `require 'dash)`.
Then remove helm-projectile.elc and restart emacs.

**Comment by xiongtx** [comment]
You must be using an older version of `helm-projectile`; the [current](https://github.com/bbatsov/helm-projectile/blob/8a2dbc973548fac89356c11d70f7f474ea1367a5/helm-projectile.el) does't use `-union` from `dash`.

**Comment by FavoRiteKK** [comment]
> You must be using an older version of `helm-projectile`; the [current](https://github.com/bbatsov/helm-projectile/blob/8a2dbc973548fac89356c11d70f7f474ea1367a5/helm-projectile.el) does't use `-union` from `dash`.

Yes. it is the one and only latest stable release (v0.14.0).
