### ISSUE TITLE
[Feature Request] - `helm-projectile-find-file-other-window`

### ISSUE THREAD

**Issue by jcs090218** [bbatsov/helm-projectile#122]
I know there is `projectile-find-file-other-window`, is there a helm version of this? I couldn't find one! Thank you!

**Comment by jcs090218** [comment]
I implemented by doing the following code.

```el
(defun jcs-helm-projectile-find-file-other-window ()
  "Find file in project to other window."
  (interactive)
  (let ((record-dd default-directory))
    (jcs-other-window-next 1 t)
    (setq default-directory record-dd)
    (call-interactively #'helm-projectile-find-file)))
```

I wish there is still a standard way from this project. :D

**Comment by xiongtx** [comment]
This is available via the actions menu (hit `TAB`) for commands like `helm-projectile-find-files`.

**Comment by jcs090218** [comment]
So there wouldn't be a standard function call for `other-window`?
