### ISSUE TITLE
[Feature request] helm-projectile-rg supports search thing-at-point

### ISSUE THREAD

**Issue by zozowell** [bbatsov/helm-projectile#125]
## Expected behavior
`helm-projectile-rg` support `thing-at-point` search like `helm-projectile-ag`.

## Actual behavior
Today, only search `selection-region` is supported by `helm-projectile-rg`, unfortunately the underlaying `helm-rg` doesn't support `thing-at-point` either.

## Steps to reproduce the problem
I don't see support in code, neither can I find any likely thing in `helm-rg`

## Environment & version information

- `helm-projectile` version: 20190408.1508
- `helm` version (in `helm-pkg.el`): 20190703.710
- `projectile` version (`M-x projectile-version`): 20190626.1315
- Emacs version (`M-x emacs-version`): 26.2
- OS: macos

**Comment by zozowell** [comment]
I made a pull request to address this request : https://github.com/bbatsov/helm-projectile/pull/126
I've been using it in daily work, everything works upto now. 

My environment : 
* helm-projectile version: 20190408.1508
* helm version (in helm-pkg.el): 20190703.710
* projectile version (M-x projectile-version): 20190626.1315
* Emacs version (M-x emacs-version): 26.2

**Comment by xiongtx** [comment]
Doesn't `helm-rg` [already support this](https://github.com/cosmicexplorer/helm-rg/blob/785a80fe5cc87e27c5ea3d00a70049028d9e2847/helm-rg.el#L689-L693)?

![helm-projectile-rg](https://user-images.githubusercontent.com/1624090/61068989-30d7ad00-a3c0-11e9-82d8-aa370bdb47e2.gif)

**Comment by zozowell** [comment]
😓 , seems yes... https://github.com/cosmicexplorer/helm-rg/blob/master/helm-rg.el#L689
It is never mentioned in the doc.
PR closed.

**Comment by xiongtx** [comment]
You shouldn't need to set that explicitly, that's the default.

**Comment by zozowell** [comment]
1 sec, I find an issue that, helm-rg search thing-at-the-point does work in an interactive mode, if you call it interactive directly, but it doesn't work when being called via `helm-projectile-rg`. 
https://github.com/cosmicexplorer/helm-rg/blob/master/helm-rg.el#L2437

So, `helm-projectile-rg` doesn't support this still. Using `helm-rg` directly doesn't solve the problem either, because it lose the power of searching within project.

**Comment by xiongtx** [comment]
Can you try #127? That should be doing the right thing while taking into account the various customizations.

**Comment by zozowell** [comment]
#127 works fine, thanks. Close #126 then.
