### ISSUE TITLE
search broken when not in root dir of project

### ISSUE THREAD

**Issue by braineo** [bbatsov/helm-projectile#131]
## Expected behavior
Can do `helm-projectile-rg` in any sub-directory in a project

## Actual behavior
b62cea69c1fc292c577935e8e58d1bf3bb258b43 listed all project files to search, helm-rg will concatenate files with current working directory which results in path not found

## Steps to reproduce the problem
open file in a sub folder of a project, do `helm-projectile-rg` and search anything

## Environment & version information

- `helm-projectile` version:
- `helm` version (in `helm-pkg.el`):
- `projectile` version (`M-x projectile-version`):
- Emacs version (`M-x emacs-version`):
- OS:

**Comment by jaux** [comment]
I have the same issue. Now I need to set `helm-rg-default-directory` to `'git-root` to workaround this issue.

**Comment by xiongtx** [comment]
Sorry about that, I've reverted the commit.

**Comment by gayanhewa** [comment]
I get this triggered every time I run `helm-projectile-rg`
```
Error running timer: (error "Candidates function ‘helm-ag--do-ag-candidate-process’ should run a process") [3 times]
```
I also have :

```
(use-package helm-rg
  :config
  (setq helm-rg-default-directory 'git-root))
```

Am I doing anything wrong?

**Comment by dubnev** [comment]
> ```
> Error running timer: (error "Candidates function ‘helm-ag--do-ag-candidate-process’ should run a process") [3 times]
> ```

@gayanhewa that error appears to pertain to the `helm-ag` package, do you have any configuration related to that (or is maybe the keybinding bound to helm-ag instead)?

**Comment by gayanhewa** [comment]
Oh 🤦‍♂ , I will try to take a look. I managed to get helm-ag to work, for the time being, I will revert my changes and reset the key bindings to check this again. 🙇
