### ISSUE TITLE
helm-projectile-ag error on linux kernel source tree

### ISSUE THREAD

**Issue by xzz53** [bbatsov/helm-projectile#132]
## Expected behavior
Starting helm-projectile-ag and typing three characters initiates ag search in the project.

## Actual behavior
When I try to do ag search in some of my projects (e.g. linux kernel source trees) I get `/usr/bin/emacs: /usr/bin/ag: Argument list too long` message instead of results.

## Steps to reproduce the problem
1. Shallow clone linux kernel source: `git clone --depth=1 https://github.com/torvalds/linux`
2. Switch to the project
3. M-x helm-projectile-ag

## Environment & version information

- `helm-projectile` version: 20190727.208
- `helm` version (in `helm-pkg.el`): 20190729.513
- `projectile` version (`M-x projectile-version`): 20190626.1315
- Emacs version (`M-x emacs-version`): GNU Emacs 26.2
- OS: Arch linux

NB
I'm sure it worked fine at least month ago.

**Comment by xiongtx** [comment]
This is caused by 6d0a740e45a862cb420e4e31474f60ce3809c136, which was an attempt to have `helm-ag` consider `.projectile`'s ignores.

I'm going to revert this as it's more important for `helm-projectile` to work on large projects. cc @maindoor.

**Comment by maindoor** [comment]
@xiongtx should we consider why we get "/usr/bin/emacs: /usr/bin/ag: Argument list too long message instead of results." instead of reverting ? 
How is considering .projectile ignores affecting this particular problem ?

**Comment by maindoor** [comment]
At least can we have a config option instead of reverting ? You can have the current implementation as default. Otherwise now my use-case is broken after an update :(
