### ISSUE TITLE
Key binding on MacOS Catalina 10.15.5

### ISSUE THREAD

**Issue by bytebunny** [bbatsov/helm-projectile#141]
## Expected behavior

The README states that key binding `C-c p h` stands for `M-x helm-projectile`.

## Actual behavior

The key binding is undefined.

## Steps to reproduce the problem

Followed this setup guide: https://tuhdo.github.io/c-ide.html

## Backtraces if necessary (`M-x toggle-debug-on-error`)

n/a

## Environment & version information

- `helm-projectile` version: 20200520.1843
- `helm` version (in `helm-pkg.el`): 20200614.1850
- `projectile` version (`M-x projectile-version`): 20200610.1221
- Emacs version (`M-x emacs-version`): GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02
- OS: MacOS Catalina 10.15.5

**Comment by bbatsov** [comment]
Good catch! That's related to an upstream in Projectile, which used to default to `C-c p`, as the prefix for all of its commands, but now this has to be specified explicitly by the users. See the docs https://docs.projectile.mx/projectile/installation.html#installation-via-package-el for more details. I'll update the README here as well.
