### ISSUE TITLE
"#134: Allow customization of grep commands." listed as an unreleased feature

### ISSUE THREAD

**Issue by laurynas-biveinis** [bbatsov/helm-projectile#144]
https://github.com/bbatsov/helm-projectile/blob/master/CHANGELOG.md lists https://github.com/bbatsov/helm-projectile/issues/134 as a new feature under "master (unreleased)", whereas actually it is present in the 1.0.0 release.

**Comment by bbatsov** [comment]
Guess we have no new features then. :-)
