### ISSUE TITLE
Helm-projectile doesn't respect `projectile-switch-project-action` (after update to Emacs 27.1)

### ISSUE THREAD

**Issue by art-solopov** [bbatsov/helm-projectile#153]
My Projectile-related config:

```lisp
(require 'projectile)
(require 'projectile-rails)
(require 'helm-projectile)

(setq projectile-switch-project-action #'projectile-dired)

(add-hook 'projectile-after-switch-project-hook 'set-ruby)
(projectile-rails-global-mode)

(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
(define-key projectile-rails-mode-map (kbd "C-c r") 'projectile-rails-command-map)

(projectile-mode +1)
(helm-projectile-on)
```

If I replace the last line with `(helm-projectile-off)`, the problem disappears.

## Expected behavior

After executing `helm-projectile-switch-project`, Emacs should open the project root in Dired.

## Actual behavior

After executing `helm-projectile-switch-project`, Emacs starts the "find file" action.

## Environment & version information

- `helm-projectile` version: 20201208.1837
- `helm` version (in `helm-pkg.el`): 20201212.627
- `projectile` version (`M-x projectile-version`): 20201210.927
- Emacs version (`M-x emacs-version`): 27.1
- OS: Ubuntu 20.04

**Comment by bbatsov** [comment]
Might be related to this change https://github.com/bbatsov/helm-projectile/commit/c622e89f7a96c36ce8315f1b2a550d8d504b3273

**Comment by johannes-mueller** [comment]
I also would like to have the old behavior back. People who prefer the `projectile-helm` interface can put 
```elisp
(defun switch-to-project-using-helm-projectile ()
    (helm-projectile))
(setq projectile-switch-project-action #'switch-to-project-using-helm-projectile)
```
into their `.emacs`.

**Comment by bbatsov** [comment]
I don't think you need this wrapper function. :-) I've stopped using Helm ages ago (these days I'm into ivy/selectrum), so I don't really think much about the changes that go into `helm-projectile`. Feel free to revert this change.

**Comment by thermopyle** [comment]
I also prefer the old behavior.

**Comment by bbatsov** [comment]
Behavior reverted.

**Comment by thermopyle** [comment]
Thanks!
