### ISSUE TITLE
Helm source ‘Projectile files’: before-init-hook Should be defined as a symbol

### ISSUE THREAD

**Issue by yuchunzhou** [bbatsov/helm-projectile#163]
![截屏2022-08-05 18 38 49](https://user-images.githubusercontent.com/109280366/183060684-2b399335-ff3f-413d-9713-7280b2425aeb.png)

**Comment by yuchunzhou** [comment]
How to avoid this warning? @dandavison

**Comment by luizalbertocviana** [comment]
I was able to correct it with the following change.

```
   (remove-hook 'helm-after-update-hook #'helm-projectile--move-to-real)
   (remove-hook 'helm-cleanup-hook #'helm-projectile--remove-move-to-real))
 
+(defun helm-source-projectile-files-list-before-init-hook ()
+  (add-hook 'helm-after-update-hook #'helm-projectile--move-to-real)
+  (add-hook 'helm-cleanup-hook #'helm-projectile--remove-move-to-real))
+
 (defvar helm-source-projectile-files-list
   (helm-build-sync-source "Projectile files"
-    :before-init-hook (lambda ()
-                        (add-hook 'helm-after-update-hook #'helm-projectile--move-to-real)
-                        (add-hook 'helm-cleanup-hook #'helm-projectile--remove-move-to-real))
+    :before-init-hook 'helm-source-projectile-files-list-before-init-hook
     :candidates (lambda ()
                   (when (projectile-project-p)
                     (with-helm-current-buffer

```

@bbatsov is this workaround good enough? Or do you have something else in mind?

**Comment by bbatsov** [comment]
I don't follow the upstream changes in Helm, so it's hard to say what's the best approach here.

**Comment by yuchunzhou** [comment]
> I was able to correct it with the following change.
> 
> ```
>    (remove-hook 'helm-after-update-hook #'helm-projectile--move-to-real)
>    (remove-hook 'helm-cleanup-hook #'helm-projectile--remove-move-to-real))
>  
> +(defun helm-source-projectile-files-list-before-init-hook ()
> +  (add-hook 'helm-after-update-hook #'helm-projectile--move-to-real)
> +  (add-hook 'helm-cleanup-hook #'helm-projectile--remove-move-to-real))
> +
>  (defvar helm-source-projectile-files-list
>    (helm-build-sync-source "Projectile files"
> -    :before-init-hook (lambda ()
> -                        (add-hook 'helm-after-update-hook #'helm-projectile--move-to-real)
> -                        (add-hook 'helm-cleanup-hook #'helm-projectile--remove-move-to-real))
> +    :before-init-hook 'helm-source-projectile-files-list-before-init-hook
>      :candidates (lambda ()
>                    (when (projectile-project-p)
>                      (with-helm-current-buffer
> ```
> 
> @bbatsov is this workaround good enough? Or do you have something else in mind?

if you patch it like this, helm projectile find file will not work ...

**Comment by luizalbertocviana** [comment]
@yuchunzhou you are right, thanks for noticing that.
Try this instead:

```
   (remove-hook 'helm-after-update-hook #'helm-projectile--move-to-real)
   (remove-hook 'helm-cleanup-hook #'helm-projectile--remove-move-to-real))
 
+(defvar helm-source-projectile-files-list-before-init-hook
+  (lambda ()
+    (add-hook 'helm-after-update-hook #'helm-projectile--move-to-real)
+    (add-hook 'helm-cleanup-hook #'helm-projectile--remove-move-to-real)))
+
 (defvar helm-source-projectile-files-list
   (helm-build-sync-source "Projectile files"
-    :before-init-hook (lambda ()
-                        (add-hook 'helm-after-update-hook #'helm-projectile--move-to-real)
-                        (add-hook 'helm-cleanup-hook #'helm-projectile--remove-move-to-real))
+    :before-init-hook 'helm-source-projectile-files-list-before-init-hook
     :candidates (lambda ()
                   (when (projectile-project-p)
                     (with-helm-current-buffer
```

**Comment by yuchunzhou** [comment]
Maybe to find the reason in upstream helm code base is the right direction, so i close this issue at present.
