### ISSUE TITLE
How to know if helm-projectile-ag search is complete

### ISSUE THREAD

**Issue by ratheesh** [bbatsov/helm-projectile#17]
Is there a way that user know that `helm-projectile-ag` has completed searching? This is important when large projects (eg. Linux kernel source) are searched. Currently I look at the hard disk LED to know if the search has ended.

Can we do something like `helm-projectile-grep` do? It displays message in the helm modeline when search is complete.

**Comment by syohex** [comment]
@ratheesh I have implemented this feature. Please see https://github.com/syohex/emacs-helm-ag/pull/231

**Comment by ratheesh** [comment]
Thank you @syohex . This really helps me.

**Comment by syohex** [comment]
I have merged its PR. If you have no problems, please close this issue.

**Comment by ratheesh** [comment]
Working as expected. Closing this issue.
