### ISSUE TITLE
helm-projectile-all error: "helm-interpret-value: Symbol must be a function or a variable"

### ISSUE THREAD

**Issue by alphapapa** [bbatsov/helm-projectile#18]
When I run `helm-projectile-all`, I get this error:

```
helm-interpret-value: helm-interpret-value: Symbol must be a function or a variable
```

I'm using the latest versions of `helm`, `projectile`, and `helm-projectile` from MELPA.

Thanks.

**Comment by pheaver** [comment]
Same here. Tested with helm 1.9.5 and helm-projectile 0.10.0 from melpa stable, as well as more recent unstable versions.

**Comment by xiongtx** [comment]
I don't see a command called `helm-projectile-all` in the [entire history](http://stackoverflow.com/a/2929502/864684) of the project. Do you mean `helm-projectile`, or maybe `helm-projectile-all-dired-buffers`?

**Comment by bbatsov** [comment]
I don't remember such command myself.

**Comment by alphapapa** [comment]
Oops, this command is part of https://github.com/spatz/helm-projectile-all.  Sorry, sometimes it's easy to forget which command is part of which addon package.  :)

**Comment by xiongtx** [comment]
Does `helm-projectile-find-file-in-known-projects` do what you want?

**Comment by alphapapa** [comment]
Yes, I think so, thanks.
