### ISSUE TITLE
helm-projectile-find-file ignores multiples of search strings

### ISSUE THREAD

**Issue by tko** [bbatsov/helm-projectile#2]
https://github.com/bbatsov/projectile/issues/768

**Comment by nloyola** [comment]
This is not a bug and this is how `helm` is meant to work. By using one or more spaces in the search term, helm separates them into multiple patterns. The candidates that show up after you type `a a` match both of these patterns. 

The behaviour can be reproduced with the following code:

```emacs-lisp
(helm :sources (helm-build-sync-source "Make a selection:"
                 :candidates '("abc.ext" "abc/abc.ext" "def.ext" "def/def.ext"))
      :buffer "*helm sync source*")
```

This issue can be closed.

**Comment by xiongtx** [comment]
If you need to filter for multiple instances of `foo`, use `foo.*foo`.
