### ISSUE TITLE
projectile-find-file-hook isn't run by helm-projectile-find-file

### ISSUE THREAD

**Issue by Kungsgeten** [bbatsov/helm-projectile#22]
The documentation of `projectile-find-file-hook` reads:

Hooks run when a file is opened with `projectile-find-file`.

However `helm-projectile-find-file` does not run the hooks, which I believe it should.

**Comment by bbatsov** [comment]
PR welcome. :-)

**Comment by Kungsgeten** [comment]
Okay, I've done my best ;)
