### ISSUE TITLE
Cannot open multiple files

### ISSUE THREAD

**Issue by oyvindeh** [bbatsov/helm-projectile#29]
When using `helm-projectile-find-file` (or `helm-projectile-grep`), I am trying to open multiple files by selecting them with M-SPC and then hitting RET. However, only the file that is marked by the cursor is opened.

I'm using GNU Emacs 24.5.1 on Mac OS X 10.11.2. Emacs is installed using Homebrew.

**Comment by xiongtx** [comment]
Marking multiple files and hitting `RET` opens them all for me.

If it still does not work for you, please use the issue template to provide more details and re-open the issue.

**Comment by oyvindeh** [comment]
Thanks, it works for me now as well.
