### ISSUE TITLE
helm-projectile-switch-project does not load cache if no project has been visited before

### ISSUE THREAD

**Issue by jwintz** [bbatsov/helm-projectile#34]
Launching a fresh instance of emacs with no buffer opened but the `*scratch*` one and using either `helm-projectile-switch-project` or `projectile-switch-project` does not provide any candidate.

**Comment by nloyola** [comment]
I no longer see this behaviour with commit afb825b1eee559e11b0d950d4f3918d3a5663862.

Can you confirm and close this issue please?
