### ISSUE TITLE
Remap the display label

### ISSUE THREAD

**Issue by FrancisMurillo** [bbatsov/helm-projectile#38]
Great package dude.

I was just wondering if you can map over the helm values as in make the label different from the value. Say I have a source item `a\b\c\d.txt` and I want to display it as `d.txt/c/b/a`? How would I do this? Rather, I was looking for a `helm-display-function` variable of sorts.

**Comment by FrancisMurillo** [comment]
After doing some hacking, instead of `:data`, `:candidates` allow for remapping.

```
(defvar helm-source-projectile-files-list
  (helm-build-in-buffer-source "Projectile files"
    :candidates (lambda ()                                      ;; Instead of :data
                  (condition-case nil
                       (projectile-current-project-files)      ;; Chance to remap the data
              (error nil)))
    :fuzzy-match helm-projectile-fuzzy-match
    :coerce 'helm-projectile-coerce-file
    :keymap helm-projectile-find-file-map
    :help-message 'helm-ff-help-message
    :mode-line helm-read-file-name-mode-line-string
    :action helm-projectile-file-actions
    )
  "Helm source definition for Projectile files.")
```

**Comment by xiongtx** [comment]
#66 makes use of `:candidates`, but I'm not sure what exactly you want out of `helm-projectile`.

Please use the issue template to provide more information and re-open the issue if necessary.
