### ISSUE TITLE
Helm version of projectile-persp-switch project.

### ISSUE THREAD

**Issue by justmytwospence** [bbatsov/helm-projectile#4]
Moving this here from https://github.com/bbatsov/projectile/issues/890#issuecomment-166112470

I'd like to get the functionality of both `helm-projectile-switch-project` and `projectile-persp-switch-project` in one command, but I can currently only manage one or the other. Is there a way to combine these?

**Comment by xiongtx** [comment]
I don't use `perspective-el` and don't really understand what you're asking for here. Can you provide more information (or, better yet, a patch)?

**Comment by alexpeits** [comment]
I managed to write a very hacky function that uses helm with persp-projectile to switch to a project. It basically creates a new perspective with a random name, uses helm-projectile to switch to a project and then sets the perspective's name to that of the project.

`
(defun my/helm-projectile-persp-switch-project ()
  (interactive)
  (persp-switch (let ((temp-charset "1234567890abcdefghijklmnopqrstuvwxyz")
                      (random-string ""))
                  (dotimes (i 6)
                    (setq random-string
                          (concat
                           random-string
                           (char-to-string (elt temp-charset (random (length temp-charset)))))
                          ))
                  random-string
                  ))
  (helm-projectile-switch-project)
  (persp-rename (projectile-project-name)))
`

(Elisp newbie, so code style is probably not so good)

**Comment by xiongtx** [comment]
@justmytwospence It seems @alexpeits's solution should work for you. Feel free to re-open if there's something you want to follow up on.
