### ISSUE TITLE
helm-projectile-ag could not work

### ISSUE THREAD

**Issue by yuandaxing** [bbatsov/helm-projectile#44]
Hi, 
         I do not know what i have updated, in .emacs.d project, helm-projectile-ag could not work. but in other cplusplus project, it works fine.
  below is my .emacs.d configure:

.projectile    it is empty.
emacs version: 24.4.1
.dir-locals.el:
((emacs-lisp-mode
  (helm-ag-use-grep-ignore-list . "elpa")
  (helm-ag-use-agignore . t)
  (helm-grep-ignored-directories . "elpa")))

i tried to debug, but i find it is not that easy.

**Comment by xiongtx** [comment]
Please use the issue template to provide more information and re-open this issue if necessary.
