### ISSUE TITLE
“helm-projectile-ag” makes emacs crashed.

### ISSUE THREAD

**Issue by moyotar** [bbatsov/helm-projectile#48]
"projectile-ag" works normally while “helm-projectile-ag” doesn't and will be crashed very easily.

OS: Windows 7
Emacs: GNU Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570
And packages are up-to-date.

**Comment by xiongtx** [comment]
Please use the issue template to provide more information, and re-open this issue if the problem is still occurring.
