### ISSUE TITLE
helm-projectile-on did not work

### ISSUE THREAD

**Issue by xDiego** [bbatsov/helm-projectile#49]
I got this error 

> Turn on helm-projectile key bindings
> ((63 "Commander help buffer." #[0 "ÂÃÄDÅÃÆÂEDCrÇ!qÈc  1@ÉÊ@A@²#cA¶ebË ÌpÍ\")Î " [projectile-commander-help-buffer projectile-commander-methods err funcall #[0 "Á!" [projectile-commander-help-buffer kill-buffer] 2 "
> 
> (fn)"] error #[257 "À" [nil] 2 "
> 
> (fn IGNORED)"] get-buffer-create "Projectile Commander Methods:
> 
> " format "%c:  %s
> " help-mode ...] 7 "
> 
> (fn)"]) (65 "Find ag on project." #[nil "ÀÁ!" [call-interactively helm-projectile-ag] 2]) (68 "Open project root in dired." #[0 "À " [projectile-dired] 1 "
> 
> (fn)"]) (82 "Regenerate the project's [e|g]tags." #[0 "À " [projectile-regenerate-tags] 1 "
> 
> (fn)"]) (84 "Find test file in project." #[0 "À " [projectile-find-test-file] 1 "
> 
> (fn)"]) (97 "Run ack on project." #[nil "ÀÁ!" [call-interactively helm-projectile-ack] 2]) (98 "Switch to project buffer." #[nil "À " [helm-projectile-switch-to-buffer] 1]) (100 "Find directory in project." #[nil "À " [helm-projectile-find-dir] 1]) (101 "Find recently visited file in project." #[nil "À " [helm-projectile-recentf] 1]) (102 "Find file in project." #[nil "À " [helm-projectile-find-file] 1]) (103 "Run grep on project." #[nil "À " [helm-projectile-grep] 1]) (106 "Find tag in project." #[0 "À " [projectile-find-tag] 1 "
> 
> (fn)"]) ...)

On my init file I have

> (require 'helm-config)
> (helm-mode 1)
> (require 'helm-projectile)
> (helm-projectile-on)

**Comment by xDiego** [comment]
I am using
helm-20160929.1313
helm-projectile-20160922.4
projectile-20160926.1133

**Comment by xiongtx** [comment]
Please provide more information with the issue template and re-open the issue if this is still occurring.
