### ISSUE TITLE
helm-projectile-on doesn't activate key bindings

### ISSUE THREAD

**Issue by cassianoleal** [bbatsov/helm-projectile#53]
My full `.emacs.d` can be found at https://github.com/cassianoleal/.emacs.d

The title basically describes the issue.

I tried manually running the function with `M-x helm-projectile-on`, and even though the message `Turn on helm-projectile key bindings` appears at the bottom of the screen, I still get `C-c p is undefined` every time I try to use the bindings.

**Comment by syohex** [comment]
You need to enable `projectile-mode` before calling it.

**Comment by cassianoleal** [comment]
Thanks @syohex .

[This](https://github.com/cassianoleal/.emacs.d/blob/master/init/init-projectile.el#L6-L10) was supposed to enable it, and it used to. It seems like something changed underneath me which caused it to stop working.

I'll close this issue now while I find the best way to deal with that.

**Comment by syohex** [comment]
```lisp
    (autoload
      'projectile-mode
      "projectile-mode"
      "Project Management"
t)
```

This makes no sense. `autoload` function is lazy loading setting and it means that `projectile-mode` is defined at `projectile-mode.el` andd you do `M-x projectile-mode` then Emacs loads `projectile-mode.el`. You should write `(projectile-mode 1)` instead of it.

**Comment by cassianoleal** [comment]
Cool, thanks. I have set out to learn Elisp properly instead of just bashing away half copy-pasted code from various sources. :)
