### ISSUE TITLE
Customize support for helm-projectile-on

### ISSUE THREAD

**Issue by nickmccurdy** [bbatsov/helm-projectile#54]
I like setting up modes in customize as much as possible. While I find `helm-projectile-on` to be very convenient, would it be possible to toggle this in a customize variable? I'm fairly new to emacs lisp, but I'm assuming that helm-projectile could automatically check if this variable is defined on startup and trigger a call of this function.

**Comment by xiongtx** [comment]
Minor modes are not usually activated through the Customize interface (I can't think of any that are).
