### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by DamienCassou** [bbatsov/helm-projectile#63]
Previous release is from last July. What about a new one?

**Comment by bbatsov** [comment]
I'll have to check whether a new release would depend on a new Projectile release. As I don't use Helm myself I've never paid this project much attention. I scratched the initial version when I was curious about Helm and afterwards it was mostly driven by contributors only. It might be idea to find a couple of more maintainers for the project. :-)

**Comment by bbatsov** [comment]
Now that @xiongtx has joined the project as co-maintainer I'll leave it to him to decide when to cut a new release.

**Comment by DamienCassou** [comment]
ping :-)

**Comment by xiongtx** [comment]
It seems that the intent is for `helm-projectile`'s version to track that of `projectile`. Since [`projectile`'s latest version is `0.14.0`](https://github.com/bbatsov/projectile/releases/tag/v0.14.0), I'm not sure we should bump `helm-projectile`.

@DamienCassou what's the need for a new release?

**Comment by DamienCassou** [comment]
I'm not using helm-projectile anymore.
