### ISSUE TITLE
helm-projectile-browse-dirty-projects bound to wrong key in projectile commander

### ISSUE THREAD

**Issue by malcolmpurvis** [bbatsov/helm-projectile#70]
The function `helm-projectile-browse-dirty-projects` is bound to the `v` key in the projectile commander. It should be bound to the `V` key instead, since in plain projectile, `V` is bound to `projectile-browse-dirty-projects` and `v` is bound to `projectile-vc`.

## Environment & version information

- `helm-projectile` version:  20170125.1815
- `helm` version (in `helm-pkg.el`): 20170128.1257
- `projectile` version (`M-x projectile-version`): Projectile 20170106.606
- Emacs version (`M-x emacs-version`): 26.0.50.2
- OS: MacOS 10.12.3

**Comment by xiongtx** [comment]
Good catch, and [resolved](https://github.com/bbatsov/helm-projectile/commit/e16da3ec6d6c495ee8355e3c3729294bdee0a57b).
