### ISSUE TITLE
helm-projectile does not find anything when running helm-projectile-grep

### ISSUE THREAD

**Issue by jamiltron** [bbatsov/helm-projectile#73]
Hello, when running `helm-projectile-grep` over a project in Windows 10 I get nothing back, even when searching over very common words such as `function` that are in unignored files.

## Expected behavior

`helm-projectile-grep` returns a list of all occurrences of the word `function` in a Lua project.

## Actual behavior

Nothing is returned, and once I press enter I get the following message: 

```
Error running timer 'helm-projectile-grep-or-ack' (wrong-type-argument stringp nil)
```

## Steps to reproduce the problem

Load a project on Windows 10, place cursor over common word, type `C-c p s g`, then hit `RET`.

### Operating System

Windows 10 Enterprise 64 bit.

### Emacs

Emacs 25.1

### Packages

helm-projectile 20170202.1000

helm 20170309.105

projectile 20170309.30

**Comment by xiongtx** [comment]
Can you provide a more complete stacktrace using [`debug-on-error`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Error-Debugging.html)?

Do you get the same result using `helm-projectile-ag`?

**Comment by jamiltron** [comment]
The output with debug-on-error is pretty long and something in it is preventing easy copy-paste, so I've uploaded the output as a text file.
[debug.txt](https://github.com/bbatsov/helm-projectile/files/877454/debug.txt)

**Comment by jamiltron** [comment]
`helm-projectile-ag` responds with `helm-ag not available`

**Comment by xiongtx** [comment]
To use `helm-projectile-ag`, install [`helm-ag`](https://github.com/syohex/emacs-helm-ag).

**Comment by xiongtx** [comment]
According to @bbatsov, `helm-projectile` was [never designed to support Windows](https://twitter.com/bbatsov/status/847051926458040321).

It uses `grep`, so if you [install Cygwin](https://cygwin.com/install.html), it should work. Haven't tested it myself yet.

**Comment by jamiltron** [comment]
I ended up installing GnuWin32 grep which I thought was part of FindUtils but I guess wasn't, and that seems to work, although very very slowely (as in, have to wait several minutes after searching for a trivial word in my project).

I am currently trying to figure out if that's an indexing issue, search space issue, my setup, or something else.
