### ISSUE TITLE
DISPLAY NOT READY

### ISSUE THREAD

**Issue by emacsun** [bbatsov/helm-projectile#78]
## Expected behavior
under a projectile with large number of files (say 6000), Helm-projectile is also expected to work with high efficiency, especially when the silver searcher is used. 

## Actual behavior
when the projectile has many files, the helm files buffer does not update when I use helm-projectile-filn-file. helm-projectile is stuck. However, when the project has several files. it works quite well

I  checked that the variable helm-exit-idle-delay is set as 0.

## Environment & version information
I update all the packages using melpa
- `helm-projectile` version: the latest version
- `helm` version (in `helm-pkg.el`): the latest version
- `projectile` version (`M-x projectile-version`): the latest version
- Emacs version (`M-x emacs-version`): 25.01
- OS:windows

**Comment by emacsun** [comment]
I found under windows only project with .git will be indexed. 
something strange, because several days ago, project with .projectile can also be indexed.

**Comment by xiongtx** [comment]
`helm-projectile` is not currently designed for use with Windows. Windows does not have ready access to commands like `grep`, for example.

How long do you have to wait for the Helm display to be ready?

**Comment by pramodhkp** [comment]
This happens in linux (Ubuntu) as well. The helm-projectile doesn't list any files and sometimes, even if it displays, clicking on a row, throws the error `Display not ready`

**Comment by xiongtx** [comment]
Yes, I've seen this happen myself. If you have a large number of files, you may have a wait a bit before Helm is able to process them all. That's a Helm issue (and I'm sure @thierryvolpiatto, the Helm maintainer, will tell you it's an Emacs limitation).

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Yes, I've seen this happen myself. If you have a large number of
> files, you may have a wait a bit before Helm is able to process them
> all. That's a Helm issue (and I'm sure @thierryvolpiatto, the Helm
> maintainer, will tell you it's an Emacs limitation).

I guess you are using read-string somewhere in your helm code, use
instead helm-read-string.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by xiongtx** [comment]
> use instead `helm-read-string`.

OK. But AFAICT this will only stop showing the `[Display not ready!]` message, but do nothing for performance.
