### ISSUE TITLE
Save helm-projectile-find-file results into a persistent buffer.

### ISSUE THREAD

**Issue by it3ration** [bbatsov/helm-projectile#80]
## Expected behavior

Executing `helm-projectile-find-file` and then typing C-x C-s should allow the user to save the search results into a persistent buffer.

## Actual behavior

I get the error `helm: Error: Trying to run helm within a running helm session`. There could also be a save action (activated when hitting TAB to get to the actions pane).

## Environment & version information

- `helm-projectile` version:
- `helm` version (in `helm-pkg.el`):
- `projectile` version (`M-x projectile-version`):
- Emacs version (`M-x emacs-version`):
- OS:

**Comment by xiongtx** [comment]
Not being able to `save-buffer` is default Helm functionality. `C-x C-s` will signal the same error when using `helm-find-files` etc.

Some modification will have to be made to [`helm-read-file-name`](https://github.com/emacs-helm/helm/blob/v2.8.4/helm-mode.el#L846) and possibly more.

As a workaround, if you `C-g` after calling `helm-projectile-find-file`, you can switch to the `*helm projectile*` buffer and see that the contents are there. Note that `helm-buffers-list`, `helm-mini` etc. will ignore internal Helm (`*helm ...*`) buffers by default, but it's still there.

**Comment by it3ration** [comment]
Ok thanks, I'll give that a try.
