### ISSUE TITLE
.dir-locals.el variables are ignored

### ISSUE THREAD

**Issue by dvzubarev** [bbatsov/helm-projectile#83]
I should use `.dir-locals.el` file for storing local project settings, according to [doc](http://projectile.readthedocs.io/en/latest/configuration/#storing-project-settings). These settings do not work with helm-projectile.
## Steps to reproduce the problem
1. Create temp project:
    `mkdir /tmp/tmp_proj && cd /tmp/tmp_proj && touch .projectile MyBinaryFile`
    `echo '((nil . ((projectile-globally-ignored-files . ("MyBinaryFile")))))' > .dir-locals.el`
2. Then open `/tmp/tmp_proj/.projectile` in emacs
3. `M-x helm-projectile-find-file`

## Expected behavior

There is no `MyBinaryFile` in candidates. 

## Actual behavior
`MyBinaryFile` is on the candidates list. `projectile-find-file` works as expected. 
I printed some information within `projectile-current-project-files` function and noticed that the current buffer has changed in [commit](https://github.com/bbatsov/helm-projectile/commit/aaee1664d26ee9c05154a2e6999ba3a3370355ed). At [commit](https://github.com/bbatsov/helm-projectile/commit/1af59795d8535f23538d2ba38016c50071d74c66): `(current-buffer)` - `.projectile` (problem is not reproducible),
at [commit](https://github.com/bbatsov/helm-projectile/commit/aaee1664d26ee9c05154a2e6999ba3a3370355ed): `(current-buffer)` - `*helm projectile*`  (problem is reproducible).

## Environment & version information

- `helm-projectile` version: 20170613.1014
- `helm` version (in `helm-pkg.el`): 20170909.613, helm-core "2.8.4"
- `projectile` version (`M-x projectile-version`): 20170416.148
- Emacs version (`M-x emacs-version`): 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.11)
- OS: Ubuntu 17.04

**Comment by xiongtx** [comment]
The problem is that, when supplying a closure to `:candidates` in `helm-build-sync-source`, the closure doesn't get the dir-local value.

I'll have to discuss how best to resolve this w/ @thierryvolpiatto.
