### ISSUE TITLE
helm-highlight-buffers: Symbol’s value as variable is void: dired-buffers

### ISSUE THREAD

**Issue by allencch** [bbatsov/helm-projectile#84]
## Expected behavior
Should show a mini-buffer that list the files of a git project based on the currently opened file.

## Actual behavior
It says
```
helm-highlight-buffers: Symbol’s value as variable is void: dired-buffers
```

## Steps to reproduce the problem
1. Create a git project with two files, example `README.md` and `hello.txt`
2. Open **both** files.
3. At either buffer, do `C-c p h` (`helm-projectile`), then the message will be shown `helm-highlight-buffers: Symbol’s value as variable is void: dired-buffers`.

## Environment & version information

- `helm-projectile` version: 20170613.14
- `helm` version (in `helm-pkg.el`): 20170917.141
- `projectile` version (`M-x projectile-version`): 20170917.410
- Emacs version (`M-x emacs-version`): 25.2.1
- OS: Linux

**Comment by marioaquino** [comment]
I get the same error.  My versions are as follows:

helm-20170926.310
helm-projectile-20170926.1123
projectile-20170917.410
GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G31)) of 2016-08-23

**Comment by Ra1nyHouse** [comment]
I get the same error.
But it looks fine after I run the command `helm-buffers-list`.

**Comment by allencch** [comment]
With the following versions:

* Emacs 25.3.1
* helm-20171028.246
* helm-projectile-20170926.1123
* projectile-20171009.848

The issue is resolved. Can be closed.
