### ISSUE TITLE
helm-projectile-grep doesn't work, but projectile-grep work well

### ISSUE THREAD

**Issue by ShualLiu** [bbatsov/helm-projectile#86]
## Expected behavior
show the filtered result

## Actual behavior
Error running timer: (error "In `Grep' source: `helm-grep-collect-candidates' 
 (void-function format-spec)")

## Steps to reproduce the problem
I was using helm-projectile to learning kubernetes source code.
M-x projectile-global-model
M-x helm-projectile-on
using helm-projectile-grep to filter file.

## Environment & version information

- `helm-projectile` version:0.14.0
- `helm` version (in `helm-pkg.el`):2.8.5
- `projectile` version (`M-x projectile-version`):0.14.0
- Emacs version (`M-x emacs-version`):24.5.1
- OS:XUbuntu 16.04.3

**Comment by ShualLiu** [comment]
e..... Now I  use helm-ag to replace this function.

**Comment by shiyuangu** [comment]
I had the same problem. Looks like that the package _format-spec_ is not loaded by _helm-projectile_. the problem is gone if I add (require 'format-spec) before loading helm.

**Comment by ShualLiu** [comment]
😏helm-ag may be a better choice.

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=http://nos.netease.com/mail-online/sm9331f671c08cac8da1866923d0e6846b.jpg&name=shualliu&uid=shualliu%40outlook.com&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ashualliu%40outlook.com%22%5D>
[http://nos.netease.com/mail-online/sm9331f671c08cac8da1866923d0e6846b.jpg]
shualliu
邮箱：shualliu@outlook.com


签名由 网易邮箱大师<http://mail.163.com/dashi/android.html?from=mail28> 定制

在2018年02月08日 10:44，shiyuangu<mailto:notifications@github.com> 写道：

I had the same problem. Looks like that the package format-spec is not loaded by helm-projectile. the problem is gone if I add (require 'format-spec) before loading helm.

**Comment by xiongtx** [comment]
`helm-projectile-grep` uses `helm-grep`; it seems `helm-grep` [uses `format-spec`](https://github.com/emacs-helm/helm/blob/98e87c46e7732a9628ae9a9a3333791edc001e95/helm-grep.el#L482) w/out `require`ing it.

I've opened emacs-helm/helm#1993 to fix that. Therefore, this can be closed.
