### ISSUE TITLE
Projectile Files out of sync when switching between projects

### ISSUE THREAD

**Issue by rymndhng** [bbatsov/helm-projectile#88]
## Expected behavior
When switching projects and then immediately invoking projectile-find-files, I expect the "projectile files" buffer to be up to date.

## Actual behavior
I see "projectile files" from the previous project. I need to re-run `helm-projectile-find-file` in order to find the updated files.

## Steps to reproduce the problem
1. Open the directory of one project project and run `helm-projectile-find-file`
2. Go to another project and run `helm-projectile-find-file`. 
3. Look at the `Projectile Files` list in helm and see files from previous project.

## Environment & version information

- `helm-projectile` version: 20170926.1123
- `helm` version (in `helm-pkg.el`): 20171020.1124
- `projectile` version (`M-x projectile-version`): 20171009.848
- Emacs version (`M-x emacs-version`):  25.3.1
- OS: Mac OS 10.11

**Comment by asok** [comment]
@rymndhng do you have `projectile-rails-global-mode` enabled?

**Comment by KMontag42** [comment]
I am seeing this same error across Ubuntu 17.10, 16.04, and OS X 10.11

**Comment by rymndhng** [comment]
@asok I do have it enabled (using spacemacs)

I worked around this by re-binding `M-m p f` to `projectile-find-file` instead of `helm-projectile-find-file`

**Comment by asok** [comment]
@rymndhng I've pushed a change. If you do use unstable melpa please update `projectile-rails` and let me know if it helped.

**Comment by KMontag42** [comment]
I am not using `projectile-rails` and am seeing this behavior when switching between projects.

Using `projectile-find-file` works for me, but not when doing `helm-persp-switch-project`. When using the latter command, it does not properly change the project files until I hit `Esc` and run `projectile-find-file`

**Comment by rymndhng** [comment]
@asok I tried the latest `projectile-rails`. It seems to have fixed the problem 👍

**Comment by KMontag42** [comment]
I reinstalled my emacs packages and it worked! Thanks so much for your fix!

**Comment by rymndhng** [comment]
I'm going to mark this as closed since updating `projectile-rails` fixes this issue.
