### ISSUE TITLE
helm-projectile-find-file stops matching if matches at a higher directory are found

### ISSUE THREAD

**Issue by ahungry** [bbatsov/helm-projectile#89]
## Expected behavior
If I run helm-projectile-find-file on a project with structure such as:

```lisp
LICENSE
src/file.lisp
```

and search the term `li`, the only candidate listed is LICENSE.

I would expect both to be listed (`src/file.lisp` won't be listed until typing at least 'lis', to invalidate the candidate match on LICENSE).

**Comment by ahungry** [comment]
Setting `(setq helm-projectile-fuzzy-match nil)` fixes the issue, so this is likely some type of problem related to the fuzzy matcher.

**Comment by xiongtx** [comment]
Cannot reproduce w/ `helm-projectile-fuzzy-match` as `t` and `helm-projectile 20180228.1125`.

Can you update to latest `helm` / `helm-projectile` and try again?

**Comment by ahungry** [comment]
I can't reproduce either, but this new issue is now present: https://github.com/bbatsov/helm-projectile/issues/99
