### ISSUE TITLE
helm-projectile-on highlighting second suggestion in helm m-x

### ISSUE THREAD

**Issue by eamonnsullivan** [bbatsov/helm-projectile#96]
I have the following in my helm configuration:
  (global-set-key (kbd "M-x") 'undefined)
  (global-set-key (kbd "M-x") 'helm-M-x)
In my projectile configuration, I have this:
  (helm-projectile-on)
  (setq projectile-completion-system 'helm)
  (setq projectile-switch-project-action 'helm-projectile-find-file)

In the latest release, when I type M-x, the *second* suggested command is highlighted, not the first one, so I have to type C-p to get the command I intended. 

If I comment out the three projectile lines above, then I get the expected behaviour.

I suspect the change in commit 
https://github.com/bbatsov/helm-projectile/commit/4b6685a4f5e07d34329c3d30924a5a64a4742948

## Expected behavior
helm-M-x should default to the first selection on the list.
## Actual behavior
helm-M-x is defaulting to the second item
## Steps to reproduce the problem
A minimal configuration of projectile (above) with helm installed, should reproduce the problem.

## Environment & version information

I am on Mac OS-X 10.12.6

- `helm-projectile` version: 20180321.324
- `helm` version (in `helm-pkg.el`): 20180321.116
- `projectile` version (`M-x projectile-version`): 20180317.2220
- Emacs version (`M-x emacs-version`): 25.3.1
- OS: Mac OS X 10.12.6

**Comment by eamonnsullivan** [comment]
The suspect commit was to fix https://github.com/bbatsov/helm-projectile/issues/42

**Comment by xiongtx** [comment]
Thanks, should be fixed.
