### ISSUE TITLE
"You're not in a project" error in outside of project

### ISSUE THREAD

**Issue by kaneuchi-ho** [bbatsov/helm-projectile#98]
## Expected behavior

Invoke helm in outside of projects, helm-projectile should not report error.

## Actual behavior

"You're not in a project" error in *Message*.

## Steps to reproduce the problem

1. Launch Emacs. (current directory is not in any project, like $HOME)
2. invoke helm

## Environment & version information

- `helm-projectile` version: 20180323.2014
- `helm` version (in `helm-pkg.el`): 20180322.2353
- `projectile` version (`M-x projectile-version`): Projectile 0.15.0snapshot (package: 20180322.415)
- Emacs version (`M-x emacs-version`):GNU Emacs 25.3.1 (x86_64-apple-darwin17.0.0, Carbon Version 158 AppKit 1561) of 2017-09-27
- OS:macOS 10.13.3

**Comment by xiongtx** [comment]
Which command are you invoking? `helm-projectile` (`C-c p h`)? If so, that should be fixed in #97.

Is your home directory actually a project? If no, then signaling `You're not in a project` is expected behavior.

**Comment by kaneuchi-ho** [comment]
Thank you for your comment.

- The command is `helm-mini`. 
- My `helm-mini-default-sources` contains `helm-source-projectile-files-list`.
- My home directory is not in a project.

I think, no error should be occurred in invoking helm-mini in this situation.

**Comment by kaneuchi-ho** [comment]
b934857b87b4c985cd07b0135322929d13cb9091 works for me, and 9ac35b814a9d3dc70a4195a8546cc06033566d42 does not.

Home this helps.

**Comment by kaneuchi-ho** [comment]
The latest version looks fine for me. Thanks!
