### ISSUE TITLE
Some change in the last week has broken helm-projectile Projectile Files area from showing files under a top level dir

### ISSUE THREAD

**Issue by ahungry** [bbatsov/helm-projectile#99]
If I run helm-projectile in a project with sub-directories, and attempt to match on a partial name match (such as 'repo'), it will exclude all non-top level candidates from the list.

Similar behavior is not shown under plain old projectile-find-file

**Comment by farva** [comment]
Happens to me as well.
I would say that it's the initial candidates list shown in the helm window that is built only from top-level files.

**Comment by ahungry** [comment]
@xiongtx this was from something you committed recently I believe

**Comment by xiongtx** [comment]
By `helm-projectile`, do you mean `helm-projectile-file`? If so, I cannot reproduce.
